import type { ScenarioKind } from "./scenarios";

export type SeedCategory =
  | "CLOTHING"
  | "SHOES"
  | "ELECTRONICS"
  | "BEAUTY"
  | "KIDS"
  | "HOME"
  | "OTHER";

export type SeedStore = {
  slug: string;
  name: string;
  domain: string;
  adapterKey: "fixture";
};

export type SeedProduct = {
  storeSlug: string;
  externalId: string;
  slug: string;
  title: string;
  brand: string;
  category: SeedCategory;
  subcategory: string;
  url: string;
  imageUrl: string;
  scenario: ScenarioKind;
};

export const seedStores: SeedStore[] = [
  { slug: "carters", name: "Carter's", domain: "carters.com", adapterKey: "fixture" },
  { slug: "lululemon", name: "lululemon", domain: "lululemon.com", adapterKey: "fixture" },
  { slug: "nike", name: "Nike", domain: "nike.com", adapterKey: "fixture" },
  { slug: "target", name: "Target", domain: "target.com", adapterKey: "fixture" },
];

export const seedProducts: SeedProduct[] = [
  {
    storeSlug: "carters",
    externalId: "crt-tee-graphic",
    slug: "toddler-graphic-tee",
    title: "Toddler Graphic Cotton Tee",
    brand: "Carter's",
    category: "KIDS",
    subcategory: "Tops",
    url: "https://www.carters.com/demo/toddler-graphic-tee",
    imageUrl: "/demo/carters.svg",
    scenario: "historicalLow",
  },
  {
    storeSlug: "carters",
    externalId: "crt-bodysuit-5",
    slug: "baby-bodysuit-5-pack",
    title: "Baby Bodysuit 5-Pack",
    brand: "Carter's",
    category: "KIDS",
    subcategory: "Baby",
    url: "https://www.carters.com/demo/baby-bodysuit-5-pack",
    imageUrl: "/demo/carters.svg",
    scenario: "saleButNotUnusual",
  },
  {
    storeSlug: "carters",
    externalId: "crt-joggers",
    slug: "kids-fleece-joggers",
    title: "Kids Fleece Joggers",
    brand: "Carter's",
    category: "KIDS",
    subcategory: "Bottoms",
    url: "https://www.carters.com/demo/kids-fleece-joggers",
    imageUrl: "/demo/carters.svg",
    scenario: "significantDrop",
  },
  {
    storeSlug: "carters",
    externalId: "crt-cardigan",
    slug: "girls-cardigan",
    title: "Girls' Soft Cardigan",
    brand: "Carter's",
    category: "KIDS",
    subcategory: "Sweaters",
    url: "https://www.carters.com/demo/girls-cardigan",
    imageUrl: "/demo/carters.svg",
    scenario: "nearHistoricalLow",
  },
  {
    storeSlug: "carters",
    externalId: "crt-oxford",
    slug: "boys-oxford-shirt",
    title: "Boys' Oxford Shirt",
    brand: "Carter's",
    category: "KIDS",
    subcategory: "Tops",
    url: "https://www.carters.com/demo/boys-oxford-shirt",
    imageUrl: "/demo/carters.svg",
    scenario: "typicalSale",
  },
  {
    storeSlug: "carters",
    externalId: "crt-sleeper",
    slug: "baby-fleece-sleeper",
    title: "Baby Fleece Sleeper",
    brand: "Carter's",
    category: "KIDS",
    subcategory: "Sleepwear",
    url: "https://www.carters.com/demo/baby-fleece-sleeper",
    imageUrl: "/demo/carters.svg",
    scenario: "stable",
  },
  {
    storeSlug: "carters",
    externalId: "crt-dress",
    slug: "toddler-twirl-dress",
    title: "Toddler Twirl Dress",
    brand: "Carter's",
    category: "KIDS",
    subcategory: "Dresses",
    url: "https://www.carters.com/demo/toddler-twirl-dress",
    imageUrl: "/demo/carters.svg",
    scenario: "yoYo",
  },
  {
    storeSlug: "carters",
    externalId: "crt-hoodie",
    slug: "kids-logo-hoodie",
    title: "Kids Logo Hoodie",
    brand: "Carter's",
    category: "KIDS",
    subcategory: "Tops",
    url: "https://www.carters.com/demo/kids-logo-hoodie",
    imageUrl: "/demo/carters.svg",
    scenario: "priceIncreased",
  },
  {
    storeSlug: "carters",
    externalId: "crt-sneakers",
    slug: "toddler-canvas-sneakers",
    title: "Toddler Canvas Sneakers",
    brand: "Carter's",
    category: "SHOES",
    subcategory: "Sneakers",
    url: "https://www.carters.com/demo/toddler-canvas-sneakers",
    imageUrl: "/demo/carters.svg",
    scenario: "shortHistory",
  },
  {
    storeSlug: "carters",
    externalId: "crt-pajamas",
    slug: "cotton-pajama-set",
    title: "Cotton Pajama Set",
    brand: "Carter's",
    category: "KIDS",
    subcategory: "Sleepwear",
    url: "https://www.carters.com/demo/cotton-pajama-set",
    imageUrl: "/demo/carters.svg",
    scenario: "historicalLow",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-align",
    slug: "align-high-rise-pant",
    title: "Align High-Rise Pant",
    brand: "lululemon",
    category: "CLOTHING",
    subcategory: "Pants",
    url: "https://shop.lululemon.com/demo/align-high-rise-pant",
    imageUrl: "/demo/lululemon.svg",
    scenario: "saleButNotUnusual",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-scuba",
    slug: "scuba-oversized-hoodie",
    title: "Scuba Oversized Hoodie",
    brand: "lululemon",
    category: "CLOTHING",
    subcategory: "Hoodies",
    url: "https://shop.lululemon.com/demo/scuba-oversized-hoodie",
    imageUrl: "/demo/lululemon.svg",
    scenario: "historicalLow",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-define",
    slug: "define-jacket",
    title: "Define Jacket",
    brand: "lululemon",
    category: "CLOTHING",
    subcategory: "Jackets",
    url: "https://shop.lululemon.com/demo/define-jacket",
    imageUrl: "/demo/lululemon.svg",
    scenario: "significantDrop",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-wunder",
    slug: "wunder-train-tight",
    title: "Wunder Train High-Rise Tight",
    brand: "lululemon",
    category: "CLOTHING",
    subcategory: "Tights",
    url: "https://shop.lululemon.com/demo/wunder-train-tight",
    imageUrl: "/demo/lululemon.svg",
    scenario: "nearHistoricalLow",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-belt-bag",
    slug: "everywhere-belt-bag",
    title: "Everywhere Belt Bag",
    brand: "lululemon",
    category: "OTHER",
    subcategory: "Bags",
    url: "https://shop.lululemon.com/demo/everywhere-belt-bag",
    imageUrl: "/demo/lululemon.svg",
    scenario: "typicalSale",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-metal-vent",
    slug: "metal-vent-tech-shirt",
    title: "Metal Vent Tech Shirt",
    brand: "lululemon",
    category: "CLOTHING",
    subcategory: "Tops",
    url: "https://shop.lululemon.com/demo/metal-vent-tech-shirt",
    imageUrl: "/demo/lululemon.svg",
    scenario: "stable",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-energy",
    slug: "energy-bra",
    title: "Energy Bra",
    brand: "lululemon",
    category: "CLOTHING",
    subcategory: "Bras",
    url: "https://shop.lululemon.com/demo/energy-bra",
    imageUrl: "/demo/lululemon.svg",
    scenario: "yoYo",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-abc",
    slug: "abc-slim-fit-pant",
    title: "ABC Slim-Fit Pant",
    brand: "lululemon",
    category: "CLOTHING",
    subcategory: "Pants",
    url: "https://shop.lululemon.com/demo/abc-slim-fit-pant",
    imageUrl: "/demo/lululemon.svg",
    scenario: "priceIncreased",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-hotty",
    slug: "hotty-hot-short",
    title: "Hotty Hot High-Rise Short",
    brand: "lululemon",
    category: "CLOTHING",
    subcategory: "Shorts",
    url: "https://shop.lululemon.com/demo/hotty-hot-short",
    imageUrl: "/demo/lululemon.svg",
    scenario: "shortHistory",
  },
  {
    storeSlug: "lululemon",
    externalId: "llu-define-crop",
    slug: "define-crop-jacket",
    title: "Define Cropped Jacket",
    brand: "lululemon",
    category: "CLOTHING",
    subcategory: "Jackets",
    url: "https://shop.lululemon.com/demo/define-crop-jacket",
    imageUrl: "/demo/lululemon.svg",
    scenario: "historicalLow",
  },
  {
    storeSlug: "nike",
    externalId: "nike-pegasus",
    slug: "pegasus-running-shoe",
    title: "Pegasus Running Shoe",
    brand: "Nike",
    category: "SHOES",
    subcategory: "Running",
    url: "https://www.nike.com/demo/pegasus-running-shoe",
    imageUrl: "/demo/nike.svg",
    scenario: "historicalLow",
  },
  {
    storeSlug: "nike",
    externalId: "nike-dri-fit",
    slug: "dri-fit-running-tee",
    title: "Dri-FIT Running Tee",
    brand: "Nike",
    category: "CLOTHING",
    subcategory: "Tops",
    url: "https://www.nike.com/demo/dri-fit-running-tee",
    imageUrl: "/demo/nike.svg",
    scenario: "typicalSale",
  },
  {
    storeSlug: "nike",
    externalId: "nike-tech-fleece",
    slug: "tech-fleece-joggers",
    title: "Tech Fleece Joggers",
    brand: "Nike",
    category: "CLOTHING",
    subcategory: "Bottoms",
    url: "https://www.nike.com/demo/tech-fleece-joggers",
    imageUrl: "/demo/nike.svg",
    scenario: "saleButNotUnusual",
  },
  {
    storeSlug: "nike",
    externalId: "nike-court",
    slug: "court-legacy-sneaker",
    title: "Court Legacy Sneaker",
    brand: "Nike",
    category: "SHOES",
    subcategory: "Lifestyle",
    url: "https://www.nike.com/demo/court-legacy-sneaker",
    imageUrl: "/demo/nike.svg",
    scenario: "significantDrop",
  },
  {
    storeSlug: "nike",
    externalId: "nike-infinity",
    slug: "infinity-react-running",
    title: "React Infinity Running Shoe",
    brand: "Nike",
    category: "SHOES",
    subcategory: "Running",
    url: "https://www.nike.com/demo/infinity-react-running",
    imageUrl: "/demo/nike.svg",
    scenario: "nearHistoricalLow",
  },
  {
    storeSlug: "nike",
    externalId: "nike-club-hoodie",
    slug: "club-fleece-hoodie",
    title: "Club Fleece Hoodie",
    brand: "Nike",
    category: "CLOTHING",
    subcategory: "Hoodies",
    url: "https://www.nike.com/demo/club-fleece-hoodie",
    imageUrl: "/demo/nike.svg",
    scenario: "stable",
  },
  {
    storeSlug: "nike",
    externalId: "nike-metcon",
    slug: "metcon-training-shoe",
    title: "Metcon Training Shoe",
    brand: "Nike",
    category: "SHOES",
    subcategory: "Training",
    url: "https://www.nike.com/demo/metcon-training-shoe",
    imageUrl: "/demo/nike.svg",
    scenario: "yoYo",
  },
  {
    storeSlug: "nike",
    externalId: "nike-windrunner",
    slug: "windrunner-jacket",
    title: "Windrunner Jacket",
    brand: "Nike",
    category: "CLOTHING",
    subcategory: "Jackets",
    url: "https://www.nike.com/demo/windrunner-jacket",
    imageUrl: "/demo/nike.svg",
    scenario: "priceIncreased",
  },
  {
    storeSlug: "nike",
    externalId: "nike-dunk",
    slug: "dunk-low-sneaker",
    title: "Dunk Low Sneaker",
    brand: "Nike",
    category: "SHOES",
    subcategory: "Lifestyle",
    url: "https://www.nike.com/demo/dunk-low-sneaker",
    imageUrl: "/demo/nike.svg",
    scenario: "shortHistory",
  },
  {
    storeSlug: "nike",
    externalId: "nike-pro-tight",
    slug: "pro-training-tight",
    title: "Pro Training Tight",
    brand: "Nike",
    category: "CLOTHING",
    subcategory: "Tights",
    url: "https://www.nike.com/demo/pro-training-tight",
    imageUrl: "/demo/nike.svg",
    scenario: "significantDrop",
  },
  {
    storeSlug: "target",
    externalId: "tgt-chino",
    slug: "goodfellow-slim-chino",
    title: "Goodfellow Slim Chino",
    brand: "Goodfellow & Co",
    category: "CLOTHING",
    subcategory: "Pants",
    url: "https://www.target.com/demo/goodfellow-slim-chino",
    imageUrl: "/demo/target.svg",
    scenario: "typicalSale",
  },
  {
    storeSlug: "target",
    externalId: "tgt-sheets",
    slug: "casaluna-sheet-set",
    title: "Casaluna Cotton Sheet Set",
    brand: "Casaluna",
    category: "HOME",
    subcategory: "Bedding",
    url: "https://www.target.com/demo/casaluna-sheet-set",
    imageUrl: "/demo/target.svg",
    scenario: "saleButNotUnusual",
  },
  {
    storeSlug: "target",
    externalId: "tgt-pillow",
    slug: "threshold-throw-pillow",
    title: "Threshold Throw Pillow",
    brand: "Threshold",
    category: "HOME",
    subcategory: "Decor",
    url: "https://www.target.com/demo/threshold-throw-pillow",
    imageUrl: "/demo/target.svg",
    scenario: "historicalLow",
  },
  {
    storeSlug: "target",
    externalId: "tgt-serum",
    slug: "good-molecules-serum",
    title: "Niacinamide Brightening Serum",
    brand: "Good Molecules",
    category: "BEAUTY",
    subcategory: "Skincare",
    url: "https://www.target.com/demo/good-molecules-serum",
    imageUrl: "/demo/target.svg",
    scenario: "significantDrop",
  },
  {
    storeSlug: "target",
    externalId: "tgt-headphones",
    slug: "heyday-on-ear-headphones",
    title: "heyday On-Ear Headphones",
    brand: "heyday",
    category: "ELECTRONICS",
    subcategory: "Audio",
    url: "https://www.target.com/demo/heyday-on-ear-headphones",
    imageUrl: "/demo/target.svg",
    scenario: "nearHistoricalLow",
  },
  {
    storeSlug: "target",
    externalId: "tgt-mixer",
    slug: "figmint-hand-mixer",
    title: "figmint Hand Mixer",
    brand: "figmint",
    category: "HOME",
    subcategory: "Kitchen",
    url: "https://www.target.com/demo/figmint-hand-mixer",
    imageUrl: "/demo/target.svg",
    scenario: "stable",
  },
  {
    storeSlug: "target",
    externalId: "tgt-candle",
    slug: "hearth-hand-candle",
    title: "Hearth & Hand Amber Candle",
    brand: "Hearth & Hand",
    category: "HOME",
    subcategory: "Decor",
    url: "https://www.target.com/demo/hearth-hand-candle",
    imageUrl: "/demo/target.svg",
    scenario: "yoYo",
  },
  {
    storeSlug: "target",
    externalId: "tgt-sneakers",
    slug: "universal-thread-sneakers",
    title: "Universal Thread Sneakers",
    brand: "Universal Thread",
    category: "SHOES",
    subcategory: "Sneakers",
    url: "https://www.target.com/demo/universal-thread-sneakers",
    imageUrl: "/demo/target.svg",
    scenario: "priceIncreased",
  },
  {
    storeSlug: "target",
    externalId: "tgt-lipstick",
    slug: "elf-lipstick",
    title: "e.l.f. Satin Lipstick",
    brand: "e.l.f.",
    category: "BEAUTY",
    subcategory: "Makeup",
    url: "https://www.target.com/demo/elf-lipstick",
    imageUrl: "/demo/target.svg",
    scenario: "shortHistory",
  },
  {
    storeSlug: "target",
    externalId: "tgt-kids-set",
    slug: "cat-jack-outfit-set",
    title: "Cat & Jack Outfit Set",
    brand: "Cat & Jack",
    category: "KIDS",
    subcategory: "Sets",
    url: "https://www.target.com/demo/cat-jack-outfit-set",
    imageUrl: "/demo/target.svg",
    scenario: "historicalLow",
  },
];
